COUNTRIES_LIST = [
    "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", 
    "Arabia Saudita", "Argelia", "Argentina", "Armenia", "Australia", "Austria", 
    "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Baréin", "Bélgica", "Belice", 
    "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana", 
    "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", 
    "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", 
    "Colombia", "Comoras", "Corea del Norte", "Corea del Sur", "Costa de Marfil", 
    "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", 
    "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", 
    "España", "Estados Unidos", "Estonia", "Etiopía", "Filipinas", "Finlandia", 
    "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", 
    "Guatemala", "Guinea", "Guinea Ecuatorial", "Guinea-Bisáu", "Guyana", "Haití", 
    "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", 
    "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", 
    "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", 
    "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", 
    "Lituania", "Luxemburgo", "Macedonia del Norte", "Madagascar", "Malasia", 
    "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio", "Mauritania", 
    "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", 
    "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", 
    "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", 
    "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", 
    "Reino Unido", "República Centroafricana", "República Checa", "República del Congo", 
    "República Democrática del Congo", "República Dominicana", "Ruanda", "Rumanía", 
    "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", 
    "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", 
    "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", 
    "Suazilandia", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza", 
    "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", 
    "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", 
    "Ucranias", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu", "Vaticano", 
    "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue"
]

DEFAULT_CURRENCIES = {
    "Afganistán": "AFN",
    "Albania": "ALL",
    "Alemania": "EUR",
    "Andorra": "EUR",
    "Angola": "AOA",
    "Antigua y Barbuda": "XCD",
    "Arabia Saudita": "SAR",
    "Argelia": "DZD",
    "Argentina": "ARS",
    "Armenia": "AMD",
    "Australia": "AUD",
    "Austria": "EUR",
    "Azerbaiyán": "AZN",
    "Bahamas": "BSD",
    "Bangladés": "BDT",
    "Barbados": "BBD",
    "Baréin": "BHD",
    "Bélgica": "EUR",
    "Belice": "BZD",
    "Benín": "XOF",
    "Bielorrusia": "BYN",
    "Birmania": "MMK",
    "Bolivia": "BOB",
    "Bosnia y Herzegovina": "BAM",
    "Botsuana": "BWP",
    "Brasil": "BRL",
    "Brunéi": "BND",
    "Bulgaria": "BGN",
    "Burkina Faso": "XOF",
    "Burundi": "BIF",
    "Bután": "BTN",
    "Cabo Verde": "CVE",
    "Camboya": "KHR",
    "Camerún": "XAF",
    "Canadá": "CAD",
    "Catar": "QAR",
    "Chad": "XAF",
    "Chile": "CLP",
    "China": "CNY",
    "Chipre": "EUR",
    "Colombia": "COP",
    "Comoras": "KMF",
    "Corea del Norte": "KPW",
    "Corea del Sur": "KRW",
    "Costa de Marfil": "XOF",
    "Costa Rica": "CRC",
    "Croacia": "EUR",
    "Cuba": "CUP",
    "Dinamarca": "DKK",
    "Dominica": "XCD",
    "Ecuador": "USD",
    "Egipto": "EGP",
    "El Salvador": "USD",
    "Emiratos Árabes Unidos": "AED",
    "Eritrea": "ERN",
    "Eslovaquia": "EUR",
    "Eslovenia": "EUR",
    "España": "EUR",
    "Estados Unidos": "USD",
    "Estonia": "EUR",
    "Etiopía": "ETB",
    "Filipinas": "PHP",
    "Finlandia": "EUR",
    "Fiyi": "FJD",
    "Francia": "EUR",
    "Gabón": "XAF",
    "Gambia": "GMD",
    "Georgia": "GEL",
    "Ghana": "GHS",
    "Granada": "XCD",
    "Grecia": "EUR",
    "Guatemala": "GTQ",
    "Guinea": "GNF",
    "Guinea Ecuatorial": "XAF",
    "Guinea-Bisáu": "XOF",
    "Guyana": "GYD",
    "Haití": "HTG",
    "Honduras": "HNL",
    "Hungría": "HUF",
    "India": "INR",
    "Indonesia": "IDR",
    "Irak": "IQD",
    "Irán": "IRR",
    "Irlanda": "EUR",
    "Islandia": "ISK",
    "Islas Marshall": "USD",
    "Islas Salomón": "SBD",
    "Israel": "ILS",
    "Italia": "EUR",
    "Jamaica": "JMD",
    "Japón": "JPY",
    "Jordania": "JOD",
    "Kazajistán": "KZT",
    "Kenia": "KES",
    "Kirguistán": "KGS",
    "Kiribati": "AUD",
    "Kuwait": "KWD",
    "Laos": "LAK",
    "Lesoto": "LSL",
    "Letonia": "EUR",
    "Líbano": "LBP",
    "Liberia": "LRD",
    "Libia": "LYD",
    "Liechtenstein": "CHF",
    "Lituania": "EUR",
    "Luxemburgo": "EUR",
    "Macedonia del Norte": "MKD",
    "Madagascar": "MGA",
    "Malasia": "MYR",
    "Malaui": "MWK",
    "Maldivas": "MVR",
    "Malí": "XOF",
    "Malta": "EUR",
    "Marruecos": "MAD",
    "Mauricio": "MUR",
    "Mauritania": "MRU",
    "México": "MXN",
    "Micronesia": "USD",
    "Moldavia": "MDL",
    "Mónaco": "EUR",
    "Mongolia": "MNT",
    "Montenegro": "EUR",
    "Mozambique": "MZN",
    "Namibia": "NAD",
    "Nauru": "AUD",
    "Nepal": "NPR",
    "Nicaragua": "NIO",
    "Níger": "XOF",
    "Nigeria": "NGN",
    "Noruega": "NOK",
    "Nueva Zelanda": "NZD",
    "Omán": "OMR",
    "Países Bajos": "EUR",
    "Pakistán": "PKR",
    "Palaos": "USD",
    "Panamá": "PAB",
    "Papúa Nueva Guinea": "PGK",
    "Paraguay": "PYG",
    "Perú": "PEN",
    "Polonia": "PLN",
    "Portugal": "EUR",
    "Reino Unido": "GBP",
    "República Centroafricana": "XAF",
    "República Checa": "CZK",
    "República del Congo": "XAF",
    "República Democrática del Congo": "CDF",
    "República Dominicana": "DOP",
    "Ruanda": "RWF",
    "Rumanía": "RON",
    "Rusia": "RUB",
    "Samoa": "WST",
    "San Cristóbal y Nieves": "XCD",
    "San Marino": "EUR",
    "San Vicente y las Granadinas": "XCD",
    "Santa Lucía": "XCD",
    "Santo Tomé y Príncipe": "STN",
    "Senegal": "XOF",
    "Serbia": "RSD",
    "Seychelles": "SCR",
    "Sierra Leona": "SLL",
    "Singapur": "SGD",
    "Siria": "SYP",
    "Somalia": "SOS",
    "Sri Lanka": "LKR",
    "Suazilandia": "SZL",
    "Sudáfrica": "ZAR",
    "Sudán": "SDG",
    "Sudán del Sur": "SSP",
    "Suecia": "SEK",
    "Suiza": "CHF",
    "Surinam": "SRD",
    "Tailandia": "THB",
    "Tanzania": "TZS",
    "Tayikistán": "TJS",
    "Timor Oriental": "USD",
    "Togo": "XOF",
    "Tonga": "TOP",
    "Trinidad y Tobago": "TTD",
    "Túnez": "TND",
    "Turkmenistán": "TMT",
    "Turquía": "TRY",
    "Tuvalu": "AUD",
    "Ucranias": "UAH",
    "Uganda": "UGX",
    "Uruguay": "UYU",
    "Uzbekistán": "UZS",
    "Vanuatu": "VUV",
    "Vaticano": "EUR",
    "Venezuela": "VES",
    "Vietnam": "VND",
    "Yemen": "YER",
    "Yibuti": "DJF",
    "Zambia": "ZMW",
    "Zimbabue": "ZWL"
}

COUNTRY_ISO_CODES = {
    "Afganistán": "AF", "Albania": "AL", "Alemania": "DE", "Andorra": "AD", "Angola": "AO",
    "Antigua y Barbuda": "AG", "Arabia Saudita": "SA", "Argelia": "DZ", "Argentina": "AR", "Armenia": "AM",
    "Australia": "AU", "Austria": "AT", "Azerbaiyán": "AZ", "Bahamas": "BS", "Bangladés": "BD",
    "Barbados": "BB", "Baréin": "BH", "Bélgica": "BE", "Belice": "BZ", "Benín": "BJ",
    "Bielorrusia": "BY", "Birmania": "MM", "Bolivia": "BO", "Bosnia y Herzegovina": "BA", "Botsuana": "BW",
    "Brasil": "BR", "Brunéi": "BN", "Bulgaria": "BG", "Burkina Faso": "BF", "Burundi": "BI",
    "Bután": "BT", "Cabo Verde": "CV", "Camboya": "KH", "Camerún": "CM", "Canadá": "CA",
    "Catar": "QA", "Chad": "TD", "Chile": "CL", "China": "CN", "Chipre": "CY",
    "Colombia": "CO", "Comoras": "KM", "Corea del Norte": "KP", "Corea del Sur": "KR", "Costa de Marfil": "CI",
    "Costa Rica": "CR", "Croacia": "HR", "Cuba": "CU", "Dinamarca": "DK", "Dominica": "DM",
    "Ecuador": "EC", "Egipto": "EG", "El Salvador": "SV", "Emiratos Árabes Unidos": "AE", "Eritrea": "ER",
    "Eslovaquia": "SK", "Eslovenia": "SI", "España": "ES", "Estados Unidos": "US", "Estonia": "EE",
    "Etiopía": "ET", "Filipinas": "PH", "Finlandia": "FI", "Fiyi": "FJ", "Francia": "FR",
    "Gabón": "GA", "Gambia": "GM", "Georgia": "GE", "Ghana": "GH", "Granada": "GD",
    "Grecia": "GR", "Guatemala": "GT", "Guinea": "GN", "Guinea Ecuatorial": "GQ", "Guinea-Bisáu": "GW",
    "Guyana": "GY", "Haití": "HT", "Honduras": "HN", "Hungría": "HU", "India": "IN",
    "Indonesia": "ID", "Irak": "IQ", "Irán": "IR", "Irlanda": "IE", "Islandia": "IS",
    "Islas Marshall": "MH", "Islas Salomón": "SB", "Israel": "IL", "Italia": "IT", "Jamaica": "JM",
    "Japón": "JP", "Jordania": "JO", "Kazajistán": "KZ", "Kenia": "KE", "Kirguistán": "KG",
    "Kiribati": "KI", "Kuwait": "KW", "Laos": "LA", "Lesoto": "LS", "Letonia": "LV",
    "Líbano": "LB", "Liberia": "LR", "Libia": "LY", "Liechtenstein": "LI", "Lituania": "LT",
    "Luxemburgo": "LU", "Macedonia del Norte": "MK", "Madagascar": "MG", "Malasia": "MY", "Malaui": "MW",
    "Maldivas": "MV", "Malí": "ML", "Malta": "MT", "Marruecos": "MA", "Mauricio": "MU",
    "Mauritania": "MR", "México": "MX", "Micronesia": "FM", "Moldavia": "MD", "Mónaco": "MC",
    "Mongolia": "MN", "Montenegro": "ME", "Mozambique": "MZ", "Namibia": "NA", "Nauru": "NR",
    "Nepal": "NP", "Nicaragua": "NI", "Níger": "NE", "Nigeria": "NG", "Noruega": "NO",
    "Nueva Zelanda": "NZ", "Omán": "OM", "Países Bajos": "NL", "Pakistán": "PK", "Palaos": "PW",
    "Panamá": "PA", "Papúa Nueva Guinea": "PG", "Paraguay": "PY", "Perú": "PE", "Polonia": "PL",
    "Portugal": "PT", "Reino Unido": "GB", "República Centroafricana": "CF", "República Checa": "CZ", "República del Congo": "CG",
    "República Democrática del Congo": "CD", "República Dominicana": "DO", "Ruanda": "RW", "Rumanía": "RO", "Rusia": "RU",
    "Samoa": "WS", "San Cristóbal y Nieves": "KN", "San Marino": "SM", "San Vicente y las Granadinas": "VC", "Santa Lucía": "LC",
    "Santo Tomé y Príncipe": "ST", "Senegal": "SN", "Serbia": "RS", "Seychelles": "SC", "Sierra Leona": "SL",
    "Singapur": "SG", "Siria": "SY", "Somalia": "SO", "Sri Lanka": "LK", "Suazilandia": "SZ",
    "Sudáfrica": "ZA", "Sudán": "SD", "Sudán del Sur": "SS", "Suecia": "SE", "Suiza": "CH",
    "Surinam": "SR", "Tailandia": "TH", "Tanzania": "TZ", "Tayikistán": "TJ", "Timor Oriental": "TL",
    "Togo": "TG", "Tonga": "TO", "Trinidad y Tobago": "TT", "Túnez": "TN", "Turkmenistán": "TM",
    "Turquía": "TR", "Tuvalu": "TV", "Ucrania": "UA", "Ucranias": "UA", "Uganda": "UG",
    "Uruguay": "UY", "Uzbekistán": "UZ", "Vanuatu": "VU", "Vaticano": "VA", "Venezuela": "VE",
    "Vietnam": "VN", "Yemen": "YE", "Yibuti": "DJ", "Zambia": "ZM", "Zimbabue": "ZW"
}

def emoji_to_country_code(emoji_str: str) -> str:
    """Extrae el código ISO de 2 letras de los símbolos regionales de un emoji de bandera."""
    if not emoji_str:
        return ""
    clean = emoji_str.strip().upper()
    if len(clean) == 2 and clean.isalpha():
        return clean
    chars = [ord(c) for c in emoji_str]
    iso_chars = [chr(c - 0x1F1E6 + ord('A')) for c in chars if 0x1F1E6 <= c <= 0x1F1FF]
    if len(iso_chars) == 2:
        return "".join(iso_chars)
    return ""

def get_country_iso_code(country_name: str, flag_emoji: str = "") -> str:
    """Obtiene el código ISO-2 en mayúsculas a partir del emoji o del nombre del país."""
    code_from_emoji = emoji_to_country_code(flag_emoji)
    if code_from_emoji:
        return code_from_emoji.upper()

    if not country_name:
        return "ES"

    clean_name = country_name.strip()
    if clean_name in COUNTRY_ISO_CODES:
        return COUNTRY_ISO_CODES[clean_name]

    c_norm = clean_name.lower()
    for name, code in COUNTRY_ISO_CODES.items():
        if name.lower() == c_norm or name.lower() in c_norm or c_norm in name.lower():
            return code

    return "ES"

def get_flag_image_url(country_name: str, flag_emoji: str = "") -> str:
    """Genera la URL de alta definición de la bandera del país vía FlagCDN."""
    iso_code = get_country_iso_code(country_name, flag_emoji).lower()
    return f"https://flagcdn.com/w160/{iso_code}.png"