COUNTRIES_LIST = [
    "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", 
    "Arabia Saudita", "Argelia", "Argentina", "Armenia", "Australia", "Austria", 
    "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Baréin", "Bélgica", "Belice", 
    "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana", 
    "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", 
    "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", 
    "Colombia", "Comoras", "Corea del Norte", "Corea del Sur", "Costa de Marfil", 
    "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", 
    "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", 
    "España", "Estados Unidos", "Estonia", "Etiopía", "Filipinas", "Finlandia", 
    "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", 
    "Guatemala", "Guinea", "Guinea Ecuatorial", "Guinea-Bisáu", "Guyana", "Haití", 
    "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", 
    "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", 
    "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", 
    "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", 
    "Lituania", "Luxemburgo", "Macedonia del Norte", "Madagascar", "Malasia", 
    "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio", "Mauritania", 
    "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", 
    "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", 
    "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", 
    "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", 
    "Reino Unido", "República Centroafricana", "República Checa", "República del Congo", 
    "República Democrática del Congo", "República Dominicana", "Ruanda", "Rumanía", 
    "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", 
    "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", 
    "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", 
    "Suazilandia", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza", 
    "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", 
    "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", 
    "Ucranias", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu", "Vaticano", 
    "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue"
]

DEFAULT_CURRENCIES = {
    "Afganistán": "AFN",
    "Albania": "ALL",
    "Alemania": "EUR",
    "Andorra": "EUR",
    "Angola": "AOA",
    "Antigua y Barbuda": "XCD",
    "Arabia Saudita": "SAR",
    "Argelia": "DZD",
    "Argentina": "ARS",
    "Armenia": "AMD",
    "Australia": "AUD",
    "Austria": "EUR",
    "Azerbaiyán": "AZN",
    "Bahamas": "BSD",
    "Bangladés": "BDT",
    "Barbados": "BBD",
    "Baréin": "BHD",
    "Bélgica": "EUR",
    "Belice": "BZD",
    "Benín": "XOF",
    "Bielorrusia": "BYN",
    "Birmania": "MMK",
    "Bolivia": "BOB",
    "Bosnia y Herzegovina": "BAM",
    "Botsuana": "BWP",
    "Brasil": "BRL",
    "Brunéi": "BND",
    "Bulgaria": "BGN",
    "Burkina Faso": "XOF",
    "Burundi": "BIF",
    "Bután": "BTN",
    "Cabo Verde": "CVE",
    "Camboya": "KHR",
    "Camerún": "XAF",
    "Canadá": "CAD",
    "Catar": "QAR",
    "Chad": "XAF",
    "Chile": "CLP",
    "China": "CNY",
    "Chipre": "EUR",
    "Colombia": "COP",
    "Comoras": "KMF",
    "Corea del Norte": "KPW",
    "Corea del Sur": "KRW",
    "Costa de Marfil": "XOF",
    "Costa Rica": "CRC",
    "Croacia": "EUR",
    "Cuba": "CUP",
    "Dinamarca": "DKK",
    "Dominica": "XCD",
    "Ecuador": "USD",
    "Egipto": "EGP",
    "El Salvador": "USD",
    "Emiratos Árabes Unidos": "AED",
    "Eritrea": "ERN",
    "Eslovaquia": "EUR",
    "Eslovenia": "EUR",
    "España": "EUR",
    "Estados Unidos": "USD",
    "Estonia": "EUR",
    "Etiopía": "ETB",
    "Filipinas": "PHP",
    "Finlandia": "EUR",
    "Fiyi": "FJD",
    "Francia": "EUR",
    "Gabón": "XAF",
    "Gambia": "GMD",
    "Georgia": "GEL",
    "Ghana": "GHS",
    "Granada": "XCD",
    "Grecia": "EUR",
    "Guatemala": "GTQ",
    "Guinea": "GNF",
    "Guinea Ecuatorial": "XAF",
    "Guinea-Bisáu": "XOF",
    "Guyana": "GYD",
    "Haití": "HTG",
    "Honduras": "HNL",
    "Hungría": "HUF",
    "India": "INR",
    "Indonesia": "IDR",
    "Irak": "IQD",
    "Irán": "IRR",
    "Irlanda": "EUR",
    "Islandia": "ISK",
    "Islas Marshall": "USD",
    "Islas Salomón": "SBD",
    "Israel": "ILS",
    "Italia": "EUR",
    "Jamaica": "JMD",
    "Japón": "JPY",
    "Jordania": "JOD",
    "Kazajistán": "KZT",
    "Kenia": "KES",
    "Kirguistán": "KGS",
    "Kiribati": "AUD",
    "Kuwait": "KWD",
    "Laos": "LAK",
    "Lesoto": "LSL",
    "Letonia": "EUR",
    "Líbano": "LBP",
    "Liberia": "LRD",
    "Libia": "LYD",
    "Liechtenstein": "CHF",
    "Lituania": "EUR",
    "Luxemburgo": "EUR",
    "Macedonia del Norte": "MKD",
    "Madagascar": "MGA",
    "Malasia": "MYR",
    "Malaui": "MWK",
    "Maldivas": "MVR",
    "Malí": "XOF",
    "Malta": "EUR",
    "Marruecos": "MAD",
    "Mauricio": "MUR",
    "Mauritania": "MRU",
    "México": "MXN",
    "Micronesia": "USD",
    "Moldavia": "MDL",
    "Mónaco": "EUR",
    "Mongolia": "MNT",
    "Montenegro": "EUR",
    "Mozambique": "MZN",
    "Namibia": "NAD",
    "Nauru": "AUD",
    "Nepal": "NPR",
    "Nicaragua": "NIO",
    "Níger": "XOF",
    "Nigeria": "NGN",
    "Noruega": "NOK",
    "Nueva Zelanda": "NZD",
    "Omán": "OMR",
    "Países Bajos": "EUR",
    "Pakistán": "PKR",
    "Palaos": "USD",
    "Panamá": "PAB",
    "Papúa Nueva Guinea": "PGK",
    "Paraguay": "PYG",
    "Perú": "PEN",
    "Polonia": "PLN",
    "Portugal": "EUR",
    "Reino Unido": "GBP",
    "República Centroafricana": "XAF",
    "República Checa": "CZK",
    "República del Congo": "XAF",
    "República Democrática del Congo": "CDF",
    "República Dominicana": "DOP",
    "Ruanda": "RWF",
    "Rumanía": "RON",
    "Rusia": "RUB",
    "Samoa": "WST",
    "San Cristóbal y Nieves": "XCD",
    "San Marino": "EUR",
    "San Vicente y las Granadinas": "XCD",
    "Santa Lucía": "XCD",
    "Santo Tomé y Príncipe": "STN",
    "Senegal": "XOF",
    "Serbia": "RSD",
    "Seychelles": "SCR",
    "Sierra Leona": "SLL",
    "Singapur": "SGD",
    "Siria": "SYP",
    "Somalia": "SOS",
    "Sri Lanka": "LKR",
    "Suazilandia": "SZL",
    "Sudáfrica": "ZAR",
    "Sudán": "SDG",
    "Sudán del Sur": "SSP",
    "Suecia": "SEK",
    "Suiza": "CHF",
    "Surinam": "SRD",
    "Tailandia": "THB",
    "Tanzania": "TZS",
    "Tayikistán": "TJS",
    "Timor Oriental": "USD",
    "Togo": "XOF",
    "Tonga": "TOP",
    "Trinidad y Tobago": "TTD",
    "Túnez": "TND",
    "Turkmenistán": "TMT",
    "Turquía": "TRY",
    "Tuvalu": "AUD",
    "Ucranias": "UAH",
    "Uganda": "UGX",
    "Uruguay": "UYU",
    "Uzbekistán": "UZS",
    "Vanuatu": "VUV",
    "Vaticano": "EUR",
    "Venezuela": "VES",
    "Vietnam": "VND",
    "Yemen": "YER",
    "Yibuti": "DJF",
    "Zambia": "ZMW",
    "Zimbabue": "ZWL"
}