export type CurrencyInfo = {
  code: string;
  name: string;
  symbol: string;
};

export const FALLBACK_COUNTRIES = [
  'España',
  'Francia',
  'Alemania',
  'Italia',
  'Portugal',
  'Reino Unido',
  'Estados Unidos',
  'México',
  'Colombia',
  'Argentina',
  'Perú',
  'Chile',
  'Brasil',
  'Canadá',
  'Japón',
  'Australia',
  'Suiza',
  'Uruguay',
  'Ecuador',
  'Bolivia',
  'Paraguay',
  'Costa Rica',
  'Panamá',
  'República Dominicana',
];

export const CURRENCY_NAMES: Record<string, { name: string; symbol: string }> = {
  EUR: { name: 'Euro', symbol: '€' },
  USD: { name: 'Dólar estadounidense', symbol: '$' },
  GBP: { name: 'Libra esterlina', symbol: '£' },
  ARS: { name: 'Peso argentino', symbol: '$' },
  MXN: { name: 'Peso mexicano', symbol: '$' },
  COP: { name: 'Peso colombiano', symbol: '$' },
  CLP: { name: 'Peso chileno', symbol: '$' },
  PEN: { name: 'Sol peruano', symbol: 'S/' },
  BRL: { name: 'Real brasileño', symbol: 'R$' },
  CAD: { name: 'Dólar canadiense', symbol: '$' },
  AUD: { name: 'Dólar australiano', symbol: '$' },
  JPY: { name: 'Yen japonés', symbol: '¥' },
  CNY: { name: 'Yuan chino', symbol: '¥' },
  CHF: { name: 'Franco suizo', symbol: 'CHF' },
  DKK: { name: 'Corona danesa', symbol: 'kr' },
  NOK: { name: 'Corona noruega', symbol: 'kr' },
  SEK: { name: 'Corona sueca', symbol: 'kr' },
  UYU: { name: 'Peso uruguayo', symbol: '$' },
  BOB: { name: 'Boliviano', symbol: 'Bs' },
  PYG: { name: 'Guaraní paraguayo', symbol: '₲' },
  DOP: { name: 'Peso dominicano', symbol: 'RD$' },
  CRC: { name: 'Colón costarricense', symbol: '₡' },
  GTQ: { name: 'Quetzal guatemalteco', symbol: 'Q' },
  HNL: { name: 'Lempira hondureño', symbol: 'L' },
  NIO: { name: 'Córdoba nicaragüense', symbol: 'C$' },
  PAB: { name: 'Balboa panameño', symbol: 'B/.' },
  VES: { name: 'Bolívar venezolano', symbol: 'Bs.' },
  EGP: { name: 'Libra egipcia', symbol: 'E£' },
  MAD: { name: 'Dírham marroquí', symbol: 'DH' },
  TRY: { name: 'Lira turca', symbol: '₺' },
  AED: { name: 'Dírham de los EAU', symbol: 'AED' },
  SAR: { name: 'Riyal saudí', symbol: '﷼' },
  INR: { name: 'Rupia india', symbol: '₹' },
  KRW: { name: 'Won surcoreano', symbol: '₩' },
  THB: { name: 'Baht tailandés', symbol: '฿' },
  IDR: { name: 'Rupia indonesia', symbol: 'Rp' },
  PHP: { name: 'Peso filipino', symbol: '₱' },
  NZD: { name: 'Dólar neozelandés', symbol: '$' },
  ZAR: { name: 'Rand sudafricano', symbol: 'R' },
  PLN: { name: 'Złoty polaco', symbol: 'zł' },
  CZK: { name: 'Corona checa', symbol: 'Kč' },
  HUF: { name: 'Forinto húngaro', symbol: 'Ft' },
  RON: { name: 'Leu rumano', symbol: 'lei' },
  BGN: { name: 'Lev búlgaro', symbol: 'лв' },
  ILS: { name: 'Nuevo séquel israelí', symbol: '₪' },
  SGD: { name: 'Dólar de Singapur', symbol: '$' },
  HKD: { name: 'Dólar de Hong Kong', symbol: '$' },
  TWD: { name: 'Nuevo dólar taiwanés', symbol: 'NT$' },
  VND: { name: 'Dong vietnamita', symbol: '₫' },
  RUB: { name: 'Rublo ruso', symbol: '₽' },
};

export const COUNTRY_CURRENCY_CODES: Record<string, string> = {
  Afganistán: 'AFN',
  Albania: 'ALL',
  Alemania: 'EUR',
  Andorra: 'EUR',
  Angola: 'AOA',
  'Antigua y Barbuda': 'XCD',
  'Arabia Saudita': 'SAR',
  Argelia: 'DZD',
  Argentina: 'ARS',
  Armenia: 'AMD',
  Australia: 'AUD',
  Austria: 'EUR',
  Azerbaiyán: 'AZN',
  Bahamas: 'BSD',
  Bangladés: 'BDT',
  Barbados: 'BBD',
  Baréin: 'BHD',
  Bélgica: 'EUR',
  Belice: 'BZD',
  Benín: 'XOF',
  Bielorrusia: 'BYN',
  Birmania: 'MMK',
  Bolivia: 'BOB',
  'Bosnia y Herzegovina': 'BAM',
  Botsuana: 'BWP',
  Brasil: 'BRL',
  Brunéi: 'BND',
  Bulgaria: 'BGN',
  'Burkina Faso': 'XOF',
  Burundi: 'BIF',
  Bután: 'BTN',
  'Cabo Verde': 'CVE',
  Camboya: 'KHR',
  Camerún: 'XAF',
  Canadá: 'CAD',
  Catar: 'QAR',
  Chad: 'XAF',
  Chile: 'CLP',
  China: 'CNY',
  Chipre: 'EUR',
  Colombia: 'COP',
  Comoras: 'KMF',
  'Corea del Norte': 'KPW',
  'Corea del Sur': 'KRW',
  'Costa de Marfil': 'XOF',
  'Costa Rica': 'CRC',
  Croacia: 'EUR',
  Cuba: 'CUP',
  Dinamarca: 'DKK',
  Dominica: 'XCD',
  Ecuador: 'USD',
  Egipto: 'EGP',
  'El Salvador': 'USD',
  'Emiratos Árabes Unidos': 'AED',
  Eritrea: 'ERN',
  Eslovaquia: 'EUR',
  Eslovenia: 'EUR',
  España: 'EUR',
  'Estados Unidos': 'USD',
  Estonia: 'EUR',
  Etiopía: 'ETB',
  Filipinas: 'PHP',
  Finlandia: 'EUR',
  Fiyi: 'FJD',
  Francia: 'EUR',
  Gabón: 'XAF',
  Gambia: 'GMD',
  Georgia: 'GEL',
  Ghana: 'GHS',
  Granada: 'XCD',
  Grecia: 'EUR',
  Guatemala: 'GTQ',
  Guinea: 'GNF',
  'Guinea Ecuatorial': 'XAF',
  'Guinea-Bisáu': 'XOF',
  Guyana: 'GYD',
  Haití: 'HTG',
  Honduras: 'HNL',
  Hungría: 'HUF',
  India: 'INR',
  Indonesia: 'IDR',
  Irak: 'IQD',
  Irán: 'IRR',
  Irlanda: 'EUR',
  Islandia: 'ISK',
  'Islas Marshall': 'USD',
  'Islas Salomón': 'SBD',
  Israel: 'ILS',
  Italia: 'EUR',
  Jamaica: 'JMD',
  Japón: 'JPY',
  Jordania: 'JOD',
  Kazajistán: 'KZT',
  Kenia: 'KES',
  Kirguistán: 'KGS',
  Kiribati: 'AUD',
  Kuwait: 'KWD',
  Laos: 'LAK',
  Lesoto: 'LSL',
  Letonia: 'EUR',
  Líbano: 'LBP',
  Liberia: 'LRD',
  Libia: 'LYD',
  Liechtenstein: 'CHF',
  Lituania: 'EUR',
  Luxemburgo: 'EUR',
  'Macedonia del Norte': 'MKD',
  Madagascar: 'MGA',
  Malasia: 'MYR',
  Malaui: 'MWK',
  Maldivas: 'MVR',
  Malí: 'XOF',
  Malta: 'EUR',
  Marruecos: 'MAD',
  Mauricio: 'MUR',
  Mauritania: 'MRU',
  México: 'MXN',
  Micronesia: 'USD',
  Moldavia: 'MDL',
  Mónaco: 'EUR',
  Mongolia: 'MNT',
  Montenegro: 'EUR',
  Mozambique: 'MZN',
  Namibia: 'NAD',
  Nauru: 'AUD',
  Nepal: 'NPR',
  Nicaragua: 'NIO',
  Níger: 'XOF',
  Nigeria: 'NGN',
  Noruega: 'NOK',
  'Nueva Zelanda': 'NZD',
  Omán: 'OMR',
  'Países Bajos': 'EUR',
  Pakistán: 'PKR',
  Palaos: 'USD',
  Panamá: 'PAB',
  'Papúa Nueva Guinea': 'PGK',
  Paraguay: 'PYG',
  Perú: 'PEN',
  Polonia: 'PLN',
  Portugal: 'EUR',
  'Reino Unido': 'GBP',
  'República Centroafricana': 'XAF',
  'República Checa': 'CZK',
  'República del Congo': 'XAF',
  'República Democrática del Congo': 'CDF',
  'República Dominicana': 'DOP',
  Ruanda: 'RWF',
  Rumanía: 'RON',
  Rusia: 'RUB',
  Samoa: 'WST',
  'San Cristóbal y Nieves': 'XCD',
  'San Marino': 'EUR',
  'San Vicente y las Granadinas': 'XCD',
  'Santa Lucía': 'XCD',
  'Santo Tomé y Príncipe': 'STN',
  Senegal: 'XOF',
  Serbia: 'RSD',
  Seychelles: 'SCR',
  'Sierra Leona': 'SLL',
  Singapur: 'SGD',
  Siria: 'SYP',
  Somalia: 'SOS',
  'Sri Lanka': 'LKR',
  Suazilandia: 'SZL',
  Sudáfrica: 'ZAR',
  Sudán: 'SDG',
  'Sudán del Sur': 'SSP',
  Suecia: 'SEK',
  Suiza: 'CHF',
  Surinam: 'SRD',
  Tailandia: 'THB',
  Tanzania: 'TZS',
  Tayikistán: 'TJS',
  'Timor Oriental': 'USD',
  Togo: 'XOF',
  Tonga: 'TOP',
  'Trinidad y Tobago': 'TTD',
  Túnez: 'TND',
  Turkmenistán: 'TMT',
  Turquía: 'TRY',
  Tuvalu: 'AUD',
  Ucrania: 'UAH',
  Ucranias: 'UAH',
  Uganda: 'UGX',
  Uruguay: 'UYU',
  Uzbekistán: 'UZS',
  Vanuatu: 'VUV',
  Vaticano: 'EUR',
  Venezuela: 'VES',
  Vietnam: 'VND',
  Yemen: 'YER',
  Yibuti: 'DJF',
  Zambia: 'ZMW',
  Zimbabue: 'ZWL',
};

export const COUNTRY_ISO_CODES: Record<string, string> = {
  Afganistán: 'AF',
  Albania: 'AL',
  Alemania: 'DE',
  Andorra: 'AD',
  Angola: 'AO',
  'Antigua y Barbuda': 'AG',
  'Arabia Saudita': 'SA',
  Argelia: 'DZ',
  Argentina: 'AR',
  Armenia: 'AM',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaiyán: 'AZ',
  Bahamas: 'BS',
  Bangladés: 'BD',
  Barbados: 'BB',
  Baréin: 'BH',
  Bélgica: 'BE',
  Belice: 'BZ',
  Benín: 'BJ',
  Bielorrusia: 'BY',
  Birmania: 'MM',
  Bolivia: 'BO',
  'Bosnia y Herzegovina': 'BA',
  Botsuana: 'BW',
  Brasil: 'BR',
  Brunéi: 'BN',
  Bulgaria: 'BG',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  Bután: 'BT',
  'Cabo Verde': 'CV',
  Camboya: 'KH',
  Camerún: 'CM',
  Canadá: 'CA',
  Catar: 'QA',
  Chad: 'TD',
  Chile: 'CL',
  China: 'CN',
  Chipre: 'CY',
  Colombia: 'CO',
  Comoras: 'KM',
  'Corea del Norte': 'KP',
  'Corea del Sur': 'KR',
  'Costa de Marfil': 'CI',
  'Costa Rica': 'CR',
  Croacia: 'HR',
  Cuba: 'CU',
  Dinamarca: 'DK',
  Dominica: 'DM',
  Ecuador: 'EC',
  Egipto: 'EG',
  'El Salvador': 'SV',
  'Emiratos Árabes Unidos': 'AE',
  Eritrea: 'ER',
  Eslovaquia: 'SK',
  Eslovenia: 'SI',
  España: 'ES',
  'Estados Unidos': 'US',
  Estonia: 'EE',
  Etiopía: 'ET',
  Filipinas: 'PH',
  Finlandia: 'FI',
  Fiyi: 'FJ',
  Francia: 'FR',
  Gabón: 'GA',
  Gambia: 'GM',
  Georgia: 'GE',
  Ghana: 'GH',
  Granada: 'GD',
  Grecia: 'GR',
  Guatemala: 'GT',
  Guinea: 'GN',
  'Guinea Ecuatorial': 'GQ',
  'Guinea-Bisáu': 'GW',
  Guyana: 'GY',
  Haití: 'HT',
  Honduras: 'HN',
  Hungría: 'HU',
  India: 'IN',
  Indonesia: 'ID',
  Irak: 'IQ',
  Irán: 'IR',
  Irlanda: 'IE',
  Islandia: 'IS',
  'Islas Marshall': 'MH',
  'Islas Salomón': 'SB',
  Israel: 'IL',
  Italia: 'IT',
  Jamaica: 'JM',
  Japón: 'JP',
  Jordania: 'JO',
  Kazajistán: 'KZ',
  Kenia: 'KE',
  Kirguistán: 'KG',
  Kiribati: 'KI',
  Kuwait: 'KW',
  Laos: 'LA',
  Lesoto: 'LS',
  Letonia: 'LV',
  Líbano: 'LB',
  Liberia: 'LR',
  Libia: 'LY',
  Liechtenstein: 'LI',
  Lituania: 'LT',
  Luxemburgo: 'LU',
  'Macedonia del Norte': 'MK',
  Madagascar: 'MG',
  Malasia: 'MY',
  Malaui: 'MW',
  Maldivas: 'MV',
  Malí: 'ML',
  Malta: 'MT',
  Marruecos: 'MA',
  Mauricio: 'MU',
  Mauritania: 'MR',
  México: 'MX',
  Micronesia: 'FM',
  Moldavia: 'MD',
  Mónaco: 'MC',
  Mongolia: 'MN',
  Montenegro: 'ME',
  Mozambique: 'MZ',
  Namibia: 'NA',
  Nauru: 'NR',
  Nepal: 'NP',
  Nicaragua: 'NI',
  Níger: 'NE',
  Nigeria: 'NG',
  Noruega: 'NO',
  'Nueva Zelanda': 'NZ',
  Omán: 'OM',
  'Países Bajos': 'NL',
  Pakistán: 'PK',
  Palaos: 'PW',
  Panamá: 'PA',
  'Papúa Nueva Guinea': 'PG',
  Paraguay: 'PY',
  Perú: 'PE',
  Polonia: 'PL',
  Portugal: 'PT',
  'Reino Unido': 'GB',
  'República Centroafricana': 'CF',
  'República Checa': 'CZ',
  'República del Congo': 'CG',
  'República Democrática del Congo': 'CD',
  'República Dominicana': 'DO',
  Ruanda: 'RW',
  Rumanía: 'RO',
  Rusia: 'RU',
  Samoa: 'WS',
  'San Cristóbal y Nieves': 'KN',
  'San Marino': 'SM',
  'San Vicente y las Granadinas': 'VC',
  'Santa Lucía': 'LC',
  'Santo Tomé y Príncipe': 'ST',
  Senegal: 'SN',
  Serbia: 'RS',
  Seychelles: 'SC',
  'Sierra Leona': 'SL',
  Singapur: 'SG',
  Siria: 'SY',
  Somalia: 'SO',
  'Sri Lanka': 'LK',
  Suazilandia: 'SZ',
  Sudáfrica: 'ZA',
  Sudán: 'SD',
  'Sudán del Sur': 'SS',
  Suecia: 'SE',
  Suiza: 'CH',
  Surinam: 'SR',
  Tailandia: 'TH',
  Tanzania: 'TZ',
  Tayikistán: 'TJ',
  'Timor Oriental': 'TL',
  Togo: 'TG',
  Tonga: 'TO',
  'Trinidad y Tobago': 'TT',
  Túnez: 'TN',
  Turkmenistán: 'TM',
  Turquía: 'TR',
  Tuvalu: 'TV',
  Ucrania: 'UA',
  Ucranias: 'UA',
  Uganda: 'UG',
  Uruguay: 'UY',
  Uzbekistán: 'UZ',
  Vanuatu: 'VU',
  Vaticano: 'VA',
  Venezuela: 'VE',
  Vietnam: 'VN',
  Yemen: 'YE',
  Yibuti: 'DJ',
  Zambia: 'ZM',
  Zimbabue: 'ZW',
};

export const getCountryCode = (country: string): string => {
  if (!country) return 'ES';
  const clean = country.trim();
  if (COUNTRY_ISO_CODES[clean]) {
    return COUNTRY_ISO_CODES[clean];
  }
  const cleanLower = clean.toLowerCase();
  for (const [name, code] of Object.entries(COUNTRY_ISO_CODES)) {
    if (name.toLowerCase() === cleanLower) {
      return code;
    }
  }
  return clean.slice(0, 2).toUpperCase();
};

export const getCurrencyInfo = (country: string): CurrencyInfo => {
  if (!country) {
    return { code: 'EUR', name: 'Euro', symbol: '€' };
  }

  const clean = country.trim();
  let code = COUNTRY_CURRENCY_CODES[clean];

  if (!code) {
    const cleanLower = clean.toLowerCase();
    for (const [name, cCode] of Object.entries(COUNTRY_CURRENCY_CODES)) {
      if (name.toLowerCase() === cleanLower) {
        code = cCode;
        break;
      }
    }
  }

  if (!code) {
    code = 'EUR';
  }

  const info = CURRENCY_NAMES[code];
  return {
    code,
    name: info?.name || code,
    symbol: info?.symbol || '$',
  };
};
